In [2]:
import numpy as np

In [3]:
X = np.ones((1,2,3,1))
padding = 2
output_channels = 1
batch_size, height, width, input_channels = X.shape
filter_size = 2
stride = 1
out_height = int((height - filter_size + 2 * padding) / stride + 1)
out_width = int((width - filter_size + 2 * padding) / stride + 1)
Y = np.zeros((batch_size, out_height, out_width, output_channels))
W = np.ones((filter_size, filter_size, input_channels, output_channels))

h_zeros = np.zeros((batch_size, padding, X.shape[2], input_channels))
X_pad = np.concatenate((h_zeros, X, h_zeros) ,axis = 1)
v_zeros = np.zeros((batch_size, X_pad.shape[1], padding, input_channels))
X_pad = np.concatenate((v_zeros, X_pad, v_zeros), axis = 2)


In [4]:
X_pad[0,:,:,0]

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [5]:
B

NameError: name 'B' is not defined

In [6]:
X = np.ones((2,2,3,1))
padding = 2
output_channels = 3
batch_size, height, width, input_channels = X.shape
filter_size = 
stride = 1.
out_height = int((height - filter_size + 2 * padding) / stride + 1)
out_width = int((width - filter_size + 2 * padding) / stride + 1)
Y = np.zeros((batch_size, out_height, out_width, output_channels))

W = np.ones((filter_size, filter_size, input_channels, output_channels))
W_reshaped = W.reshape(filter_size * filter_size * input_channels, output_channels)

h_zeros = np.zeros((batch_size, padding, X.shape[2], input_channels))
X_pad = np.concatenate((h_zeros, X, h_zeros) ,axis = 1)
v_zeros = np.zeros((batch_size, X_pad.shape[1], padding, input_channels))
X_pad = np.concatenate((v_zeros, X_pad, v_zeros), axis = 2)



for y in range(out_height):
            for x in range(out_width):
                window = X_pad[:,y:y + filter_size, x:x + filter_size,:]
                window = window.reshape(batch_size, filter_size * filter_size * input_channels)
                Y[:,y,x,:] = np.dot(window, W_reshaped)
                pass
            
print(Y[0,:,:,2])                      

SyntaxError: invalid syntax (<ipython-input-6-e0b64a2b226f>, line 5)

In [7]:
output_channels = 2
batch_size = 3

In [8]:
B = np.ones(output_channels)


In [9]:
np.concatenate([B.reshape(1,-1)]*batch_size).shape

(3, 2)

In [10]:
np.dot(window,W_reshaped).reshape(batch_size, 1, 1, output_channels).shape

NameError: name 'window' is not defined

In [11]:
X_pad[0:2, 0:2]

array([[[[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.]]]])

In [12]:
X_pad

array([[[[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [1.],
         [1.],
         [1.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [1.],
         [1.],
         [1.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.]]]])

In [13]:
X.flatten()

array([1., 1., 1., 1., 1., 1.])

In [14]:
a = np.concatenate([i* B.reshape(1,-1) for i in range(1,4)])
a

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

In [15]:
c =a.reshape((1,-1))
c[0,0] = 10

In [16]:
c

array([[10.,  1.,  2.,  2.,  3.,  3.]])

In [17]:
a

array([[10.,  1.],
       [ 2.,  2.],
       [ 3.,  3.]])

In [18]:
c.reshape((3,2))

array([[10.,  1.],
       [ 2.,  2.],
       [ 3.,  3.]])

In [21]:
np.sum(a,axis = 1)

array([11.,  4.,  6.])

In [26]:

b

array([[10.,  1.],
       [ 2.,  2.]])

In [30]:
b = a[0:2,:]
b = 2 * b
b

array([[20.,  2.],
       [ 4.,  4.]])

In [28]:
a

array([[10.,  1.],
       [ 2.,  2.],
       [ 3.,  3.]])

In [34]:
X_pad[0,padding:-padding,padding:-padding,0]

array([[1., 1., 1.],
       [1., 1., 1.]])