In [1]:
import numpy as np

In [3]:
X = np.ones((1,2,3,1))
padding = 2
output_channels = 1
batch_size, height, width, input_channels = X.shape
filter_size = 2
stride = 1
out_height = int((height - filter_size + 2 * padding) / stride + 1)
out_width = int((width - filter_size + 2 * padding) / stride + 1)
Y = np.zeros((batch_size, out_height, out_width, output_channels))
W = np.ones((filter_size, filter_size, input_channels, output_channels))

h_zeros = np.zeros((batch_size, padding, X.shape[2], input_channels))
X_pad = np.concatenate((h_zeros, X, h_zeros) ,axis = 1)
v_zeros = np.zeros((batch_size, X_pad.shape[1], padding, input_channels))
X_pad = np.concatenate((v_zeros, X_pad, v_zeros), axis = 2)


In [4]:
X_pad[0,:,:,0]

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [129]:
B

array([[0., 0.],
       [0., 0.]])

In [158]:
X = np.ones((2,2,3,1))
padding = 2
output_channels = 3
batch_size, height, width, input_channels = X.shape
filter_size = 
stride = 1.
out_height = int((height - filter_size + 2 * padding) / stride + 1)
out_width = int((width - filter_size + 2 * padding) / stride + 1)
Y = np.zeros((batch_size, out_height, out_width, output_channels))

W = np.ones((filter_size, filter_size, input_channels, output_channels))
W_reshaped = W.reshape(filter_size * filter_size * input_channels, output_channels)

h_zeros = np.zeros((batch_size, padding, X.shape[2], input_channels))
X_pad = np.concatenate((h_zeros, X, h_zeros) ,axis = 1)
v_zeros = np.zeros((batch_size, X_pad.shape[1], padding, input_channels))
X_pad = np.concatenate((v_zeros, X_pad, v_zeros), axis = 2)



for y in range(out_height):
            for x in range(out_width):
                window = X_pad[:,y:y + filter_size, x:x + filter_size,:]
                window = window.reshape(batch_size, filter_size * filter_size * input_channels)
                Y[:,y,x,:] = np.dot(window, W_reshaped)
                pass
            
print(Y[0,:,:,2])                      

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 2. 1. 0.]
 [0. 2. 4. 4. 2. 0.]
 [0. 1. 2. 2. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [48]:
output_channels = 2
batch_size = 3

In [49]:
B = np.ones(output_channels)


In [52]:
np.concatenate([B.reshape(1,-1)]*batch_size).shape

(3, 2)

In [152]:
np.dot(window,W_reshaped).reshape(batch_size, 1, 1, output_channels).shape

(2, 1, 1, 3)

In [144]:
X_pad[0:2, 0:2]

array([[[[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.]]]])

In [46]:
X_pad

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [136]:
X.flatten()

array([1., 1., 1., 1., 1., 1.])

In [64]:
a = np.concatenate([i* B.reshape(1,-1) for i in range(1,4)])
a

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

In [65]:
c =a.reshape((1,-1))
c[0,0] = 10

In [66]:
c

array([[10.,  1.,  2.,  2.,  3.,  3.]])

In [67]:
a

array([[10.,  1.],
       [ 2.,  2.],
       [ 3.,  3.]])

In [70]:
c.reshape((3,2))

array([[10.,  1.],
       [ 2.,  2.],
       [ 3.,  3.]])