In [1]:
import numpy as np
import linear_classifer

In [2]:
batch_size = 4
classes_num = 3
y=np.arange(batch_size * classes_num).reshape(batch_size,classes_num)
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
a=[]
a.append(1)
a.append(1)
a

[1, 1]

In [6]:
np.where(y == 1, 10, y)

array([[ 0, 10,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [4]:
np.max(y, axis = 1).reshape(batch_size, -1)

array([[ 2],
       [ 5],
       [ 8],
       [11]])

In [44]:
target_index = np.random.randint(0, high =classes_num,  size =batch_size )
target_index

array([1, 1, 0, 0])

In [48]:
(target_index.reshape((batch_size,-1)) == np.arange(classes_num)) +1

array([[1, 2, 1],
       [1, 2, 1],
       [2, 1, 1],
       [2, 1, 1]])

In [39]:
relevant_probs = np.take_along_axis(y, target_index.reshape((batch_size,-1)), axis = 1)

In [34]:
target_index.reshape((batch_size,-1))

array([[1],
       [2]])

In [40]:
relevant_probs

array([[ 2],
       [ 3],
       [ 6],
       [11]])

In [42]:
-np.sum(np.log(relevant_probs))

-5.981414211254481

In [46]:
(target_index[0] == np.arange(classes_num)).astype(int)

array([0, 1, 0])